### PR TITLE
chore: Include typings in npm release

### PR DESCRIPTION
**Pull request by SilviaZeta**
# Description
Include "typings" folder in npm release.

# Dependency changes
No

### CODE REVIEW

**Review by cooper667 — APPROVED** [review]

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Do we need to commit the typings folder and remove it from all the .ignores?

**Comment by SilviaZeta** [comment]
> Do we need to commit the typings folder and remove it from all the .ignores?

Yes! So.. the "files" property in package.json is an accept-list, while .npmignore is an exclude-list (these two do not work on files that are included by default by npm). I find it easier to work with an accept-list, because new files will be added to the repo and it's easy to forget about .npmignore. Ok if i delete .npmignore?

**Comment by ChasNelson1990** [comment]
> > Do we need to commit the typings folder and remove it from all the .ignores?
> 
> Yes! So.. the "files" property in package.json is an accept-list, while .npmignore is an exclude-list (these two do not work on files that are included by default by npm). I find it easier to work with an accept-list, because new files will be added to the repo and it's easy to forget about .npmignore. Ok if i delete .npmignore?

Happy for you to delete .npmignore if it's not needed... is the typings folder generated by the publish action then? So we don't need to add it explicitly to the repo?

**Comment by SilviaZeta** [comment]
> Happy for you to delete .npmignore if it's not needed... is the typings folder generated by the publish action then? So we don't need to add it explicitly to the repo?

Done! Yes, it's autogenerated by webpack in the build action and somehow it's available to the publish action (possibly).

**Review by ChasNelson1990 — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]

**Pull request merged**
