### PR TITLE
feat: Image I/O as standalone

### PR DESCRIPTION
**Pull request by SilviaZeta**
# Description

With this PR we publish the upload image React component to the Github Container Registry, in order to reuse it. The package will be private.

The lint-build-test workflow fails, because we don't have any tests for now. Not sure if it makes sense to make it pass when no tests are present or just get rid of the test part?

closes https://github.com/gliff-ai/annotate/issues/92

# Dependency changes

All packages in annotate

# Testing
No

# Documentation
N/A

### CODE REVIEW

**Comment by cooper667** [comment]
> The lint-build-test workflow fails, because we don't have any tests for now. Not sure if it makes sense to make it pass when no tests are present or just get rid of the test part?

https://github.com/gliff-ai/curate/blob/main/package.json#L15

I add "passWithNoTests" just because it keeps all of these types of build/deploy files the same

**Comment by cooper667** [comment]
Added skip tests and NPM publish on merge

**Review by cooper667 — CHANGES_REQUESTED** [review]
Can we have a README with props etc pls?

**Review by ChasNelson1990 — DISMISSED** [review]

**Review by ChrisBaidoo — APPROVED** [review]

**Comment by SilviaZeta** [comment]
> > The lint-build-test workflow fails, because we don't have any tests for now. Not sure if it makes sense to make it pass when no tests are present or just get rid of the test part?
> 
> https://github.com/gliff-ai/curate/blob/main/package.json#L15
> 
> I add "passWithNoTests" just because it keeps all of these types of build/deploy files the same

Thanks!!

**Review by ChasNelson1990 — APPROVED** [review]

**Review by cooper667 — APPROVED** [review]

**Pull request merged**
